name: my-gha
run-name: ${{github.actor}} ${{github.sha}}
description: not real, its dummy
on: push

jobs:
  my-checkout-job:
    name: this job makes artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - uses: actions/upload-artifact
        with:
          name: my-artifact
          path: artifacts

