name: my-gha
run-name: my new run as ${{github.actor}} ${{github.sha}}
description: not real, its dummy
on: push

jobs:
  my-checkout-job:
    name: this job checks out my repo and lists it
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: caching my cache directory
        uses: actions/cache@v4
        with:
          path: cache
          key: my-key

      - name: list repo contents
        run: ls -la
