name: "Autocompleted Workflow"
run-name: Run by ${{github.actor}} in the branch of ${{github.ref}}
on: [push]
jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
            - name: get food
              run: echo "hello world"
