name: my-workflow
run-name: my id is ${{github.actor_id}}
on: push
env:
  MYVAR: this is myvar value
jobs:
  my-job:
    name: asdf
    if: 5 > 4
    runs-on: ubuntu-latest
    steps:
      - name: my first step
        run: echo "check out my token ${{github.token}} and also my env value; $MYVAR"

